#!/usr/bin/env python3
"""
Vinay Kumar Mandadi — University Database v3
128+ universities | 21 regions | CS / AI / ML / Cloud / DevOps / Software only
Profile: CGPA ~7.0, GRE 324 (Q:168), 6 Oracle Certs (2 Professional), 4 Research Papers
Last updated: June 2026
"""

PROFILE = {
    "name": "Vinay Kumar Mandadi",
    "cgpa_current": 6.7,
    "cgpa_expected": 7.0,
    "gre_total": 324,
    "gre_quant": 168,
    "oracle_certs": 6,                  # 2 Professional + 4 Associate/Specialist
    "oracle_professional": 2,           # OCI Multicloud Architect Pro + OCI DevOps Pro
    "research_papers": 4,               # 8BIC(accepted) + ICMACC + PIMRC + WSSE
    "papers_accepted": 1,               # 8BIC 2026 deepfake detection (co-author)
    "papers_submitted": 3,              # AIRIMF(ICMACC), NetOps-XAI(PIMRC+IS26), GHA CI(WSSE)
    "zenodo_preprints": 2,              # AIRIMF DOI:10.5281/zenodo.20691021
                                        # NetOps-XAI DOI:10.5281/zenodo.20698544
    "japanese_levels": 3,
    "gdg_finalist": True,               # Top 3% nationally, #105 of 3700+ teams
    "google_diamond_league": True,      # 20,802 pts, 80 labs, 25 courses
    "kaggle_capstone": True,            # Veridian — AI Agents Intensive Capstone 2026
    "email": "mvkchowdary20@gmail.com",
    "github": "github.com/vinaykumarchowdary18",
    "google_dev": "g.dev/MVKchowdary18",
    "docs_ready": ["Passport", "Transcript", "MOI", "CV", "LOR x2", "GRE Score Report"],
    "docs_pending": ["TOEFL (June 2026)", "APS cert Germany", "Police cert (China only)", "Health cert (China only)"],
    "target_programs": [
        "Cloud Computing", "DevOps", "AI", "Machine Learning",
        "Data Science", "Software Engineering", "Computer Science",
        "Cybersecurity", "Information Technology", "Knowledge Science",
        "Software Analytics", "AIOps",
    ],
    "target_professors": {
        "JP": ["Yasutaka Kamei (Kyushu)", "Fumio Machida (Tsukuba)"],
        "SG": ["David Lo (SMU)"],
        "KR": ["Shin Yoo (KAIST)"],
    },
}

# Chance calculation helper
def calc_chance(gpa_min_pct, toefl_needed, aps_needed, police_needed, medical_needed,
                qs_rank_num, notes=""):
    """Returns a chance string based on Vinay's profile vs requirements."""
    base = 80
    if gpa_min_pct:
        gap = PROFILE["cgpa_expected"] * 10 - gpa_min_pct
        if gap < -5:   base -= 30
        elif gap < 0:  base -= 15
        elif gap < 5:  base -= 5
    if qs_rank_num and qs_rank_num < 50:   base -= 20
    elif qs_rank_num and qs_rank_num < 100: base -= 10
    elif qs_rank_num and qs_rank_num < 200: base -= 5
    if police_needed or medical_needed: base -= 40  # blocked
    if base >= 80: return "High"
    if base >= 60: return "Medium-High"
    if base >= 45: return "Medium"
    if base >= 30: return "Reach"
    return "Blocked"

UNIVERSITIES = [

    # ══════════════════════════════════════════════════════════
    # 🇷🇺  RUSSIA  (7 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"RU01","name":"HSE University","country":"Russia","city":"Moscow","flag":"🇷🇺",
     "qs_rank":"440","qs_num":440,
     "program":"MSc Data Science / MSc AI / MSc Software Engineering",
     "stream":"AI · ML · Software","check_url":"https://admissions.hse.ru/en/graduate-apply/",
     "known_open":"2026-06-20","known_deadline":"2026-08-08",
     "tuition":"~₹2–3L/yr","language":"MOI — no TOEFL",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Portal opens Jun 20. JetBrains/Yandex recruit here. Letter only — career limited.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","Motivation Letter"]},

    {"id":"RU02","name":"MSU Lomonosov","country":"Russia","city":"Moscow","flag":"🇷🇺",
     "qs_rank":"87","qs_num":87,
     "program":"MSc Computational Mathematics / MSc CS / MSc Applied Data Analysis",
     "stream":"AI · ML · Software","check_url":"https://www.openday.msu.ru/en/admissions",
     "known_open":"2026-06-20","known_deadline":"2026-08-10",
     "tuition":"~₹2–3L/yr","language":"MOI / Duolingo 110+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"QS #87 globally. Entrance exam required (online, math/CS).",
     "docs":["Passport","Transcript","MOI","CV","Essay"]},

    {"id":"RU03","name":"MIPT","country":"Russia","city":"Dolgoprudny","flag":"🇷🇺",
     "qs_rank":"290","qs_num":290,
     "program":"MSc Applied Math & CS / MSc AI Technologies",
     "stream":"AI · ML · Software","check_url":"https://mipt.ru/english/edu/postgraduate/",
     "known_open":"2026-06-01","known_deadline":"2026-07-31",
     "tuition":"~₹2–3L/yr","language":"TOEFL 80+ / MOI",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Russia's MIT equivalent for CS/Physics. Strong research.",
     "docs":["Passport","Transcript","MOI/TOEFL","CV","2 LORs"]},

    {"id":"RU04","name":"Saint Petersburg State University","country":"Russia","city":"Saint Petersburg","flag":"🇷🇺",
     "qs_rank":"336","qs_num":336,
     "program":"MSc Software Engineering / MSc Applied Mathematics",
     "stream":"Software · AI","check_url":"https://spbu.ru/en/education/graduate-programs",
     "known_open":"2026-06-01","known_deadline":"2026-07-31",
     "tuition":"~₹2–3L/yr","language":"MOI / TOEFL 79+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Most beautiful Russian city. Strong CS faculty.",
     "docs":["Passport","Transcript","MOI","CV"]},

    {"id":"RU05","name":"Novosibirsk State University","country":"Russia","city":"Novosibirsk","flag":"🇷🇺",
     "qs_rank":"231","qs_num":231,
     "program":"MSc CS / MSc IT / MSc AI",
     "stream":"AI · CS","check_url":"https://www.nsu.ru/n/international-relations/",
     "known_open":"2026-05-01","known_deadline":"2026-08-01",
     "tuition":"~₹1.5–2L/yr","language":"MOI / TOEFL 79+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Russia's 3rd best university. Akademgorodok science city.",
     "docs":["Passport","Transcript","MOI","CV"]},

    {"id":"RU06","name":"Ural Federal University","country":"Russia","city":"Yekaterinburg","flag":"🇷🇺",
     "qs_rank":"601-800","qs_num":700,
     "program":"MSc CS / MSc IT Systems",
     "stream":"Software · CS","check_url":"https://urfu.ru/en/international/",
     "known_open":"2026-06-01","known_deadline":"2026-08-15",
     "tuition":"~₹1–2L/yr","language":"MOI / Duolingo 105+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Safety net. Near-guaranteed admission.",
     "docs":["Passport","Transcript","MOI","CV"]},

    {"id":"RU07","name":"Kazan Federal University","country":"Russia","city":"Kazan","flag":"🇷🇺",
     "qs_rank":"601-800","qs_num":700,
     "program":"MSc Data Science / MSc CS",
     "stream":"Data Science · CS","check_url":"https://kpfu.ru/en",
     "known_open":"2026-06-01","known_deadline":"2026-08-20",
     "tuition":"~₹1–2L/yr","language":"MOI",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"N/A Russia","chance":"High",
     "notes":"Safety net. Large Indian student community.",
     "docs":["Passport","Transcript","MOI","CV"]},

    # ══════════════════════════════════════════════════════════
    # 🇬🇧  UNITED KINGDOM  (15 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"UK01","name":"University of Edinburgh","country":"UK","city":"Edinburgh","flag":"🇬🇧",
     "qs_rank":"27","qs_num":27,
     "program":"MSc AI / MSc Data Science / MSc CS",
     "stream":"AI · ML · Cloud","check_url":"https://www.ed.ac.uk/studying/postgraduate",
     "known_open":"2025-09-01","known_deadline":"2026-07-31",
     "tuition":"£38,000/yr (~₹42L)","language":"TOEFL 100 / IELTS 7.0",
     "gpa_min_pct":70,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"Reach",
     "notes":"QS #27. 4 papers + GRE 168Q are differentiators.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK02","name":"University of Manchester","country":"UK","city":"Manchester","flag":"🇬🇧",
     "qs_rank":"32","qs_num":32,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc DevOps",
     "stream":"AI · ML · DevOps · CS","check_url":"https://www.manchester.ac.uk/study/masters/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"£32,250/yr (~₹36L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"Medium-High",
     "notes":"QS #32. 65% minimum — you clear at 7.0. Jan 2027 intake available.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK03","name":"University of Bristol","country":"UK","city":"Bristol","flag":"🇬🇧",
     "qs_rank":"54","qs_num":54,
     "program":"MSc CS / MSc Data Science / MSc AI",
     "stream":"AI · CS · Data","check_url":"https://www.bristol.ac.uk/study/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"£29,000/yr (~₹32L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Think Big Scholarship up to £26,000. 60% minimum.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK04","name":"University of Glasgow","country":"UK","city":"Glasgow","flag":"🇬🇧",
     "qs_rank":"67","qs_num":67,
     "program":"MSc CS / MSc Data Science / MSc AI / MSc Software Dev",
     "stream":"AI · CS · Software","check_url":"https://www.gla.ac.uk/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"£25,750/yr (~₹28L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Cheapest UK top-70. Sep + Jan intakes.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK05","name":"University of Southampton","country":"UK","city":"Southampton","flag":"🇬🇧",
     "qs_rank":"78","qs_num":78,
     "program":"MSc AI / MSc CS / MSc Data Science / MSc Cybersecurity",
     "stream":"AI · CS · Cyber","check_url":"https://www.southampton.ac.uk/courses/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"£28,000/yr (~₹31L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Your NetOps-XAI paper relevant to their security labs.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK06","name":"University of Leeds","country":"UK","city":"Leeds","flag":"🇬🇧",
     "qs_rank":"82","qs_num":82,
     "program":"MSc AI / MSc Data Science / MSc CS / MSc Cloud Computing",
     "stream":"AI · Cloud · Data","check_url":"https://courses.leeds.ac.uk/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"£26,000/yr (~₹29L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Strong Cloud Computing MSc — perfect match.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK07","name":"Queen Mary University of London","country":"UK","city":"London","flag":"🇬🇧",
     "qs_rank":"127","qs_num":127,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.qmul.ac.uk/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"£24,625/yr (~₹27L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"London — Google DeepMind, Amazon, Meta nearby. Cheapest top-130 UK.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK08","name":"Newcastle University","country":"UK","city":"Newcastle","flag":"🇬🇧",
     "qs_rank":"148","qs_num":148,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Cloud Computing",
     "stream":"AI · Cloud · CS","check_url":"https://www.ncl.ac.uk/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"£26,400/yr (~₹29L)","language":"TOEFL 87 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Strong Cloud Computing MSc. Rolling admissions.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK09","name":"University of Kent","country":"UK","city":"Canterbury","flag":"🇬🇧",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Cybersecurity",
     "stream":"AI · Cyber · CS","check_url":"https://www.kent.ac.uk/courses/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"£19,500/yr (~₹21L)","language":"TOEFL 85 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Lower bar. 55% min. Affordable tuition.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK10","name":"University of Essex","country":"UK","city":"Colchester","flag":"🇬🇧",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Cloud Computing",
     "stream":"AI · Cloud · CS","check_url":"https://www.essex.ac.uk/courses/",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"£19,490/yr (~₹21L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"One of easiest UK unis for your profile. Strong Cloud MSc.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"UK11","name":"Coventry University","country":"UK","city":"Coventry","flag":"🇬🇧",
     "qs_rank":"801-1000","qs_num":900,
     "program":"MSc CS / MSc AI / MSc DevOps / MSc Cloud Computing",
     "stream":"DevOps · Cloud · AI","check_url":"https://www.coventry.ac.uk/course-structure/pg/",
     "known_open":"2025-10-01","known_deadline":"2026-09-30",
     "tuition":"£17,800/yr (~₹19L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":50,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"MSc DevOps + Cloud Computing — perfect program match. January intake available.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"UK12","name":"University of Hertfordshire","country":"UK","city":"Hatfield","flag":"🇬🇧",
     "qs_rank":"801-1000","qs_num":900,
     "program":"MSc CS / MSc AI / MSc Cloud Computing",
     "stream":"Cloud · AI · CS","check_url":"https://www.herts.ac.uk/courses/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-09-30",
     "tuition":"£14,500/yr (~₹16L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":50,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Cheapest UK Cloud MSc. Near London.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"UK13","name":"Northumbria University","country":"UK","city":"Newcastle","flag":"🇬🇧",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Cybersecurity",
     "stream":"AI · Cyber · Data","check_url":"https://www.northumbria.ac.uk/study-at-northumbria/courses/",
     "known_open":"2025-10-01","known_deadline":"2026-09-30",
     "tuition":"£17,500/yr (~₹19L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"High acceptance rate. Rolling admissions.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"UK14","name":"University of Stirling","country":"UK","city":"Stirling","flag":"🇬🇧",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://www.stir.ac.uk/postgraduate/",
     "known_open":"2025-10-01","known_deadline":"2026-09-30",
     "tuition":"£17,000/yr (~₹19L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"Scotland. Affordable. Rolling admissions.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"UK15","name":"Brunel University London","country":"UK","city":"London","flag":"🇬🇧",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Data Science & Analytics",
     "stream":"AI · Data · CS","check_url":"https://www.brunel.ac.uk/computer-science/postgraduate",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"£19,500/yr (~₹21L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr UK Graduate visa","chance":"High",
     "notes":"London location with accessible entry requirements.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇮🇪  IRELAND  (7 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"IE01","name":"University of Galway","country":"Ireland","city":"Galway","flag":"🇮🇪",
     "qs_rank":"326","qs_num":326,
     "program":"MSc CS — Artificial Intelligence",
     "stream":"AI · ML · NLP","check_url":"https://www.universityofgalway.ie/courses/taught-postgraduate-courses/computer-science-artificial-intelligence.html",
     "known_open":"2026-01-01","known_deadline":"2026-07-31",
     "tuition":"€16,750/yr (~₹15L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"High",
     "notes":"CONFIRMED OPEN — Jul 31 deadline. Apply now, add TOEFL when ready. Google/Apple EU HQs in Ireland.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL (pending ok)"]},

    {"id":"IE02","name":"DCU — Dublin City University","country":"Ireland","city":"Dublin","flag":"🇮🇪",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc Computing — AI / Cloud / DevOps / Software",
     "stream":"AI · Cloud · DevOps · Software","check_url":"https://www.dcu.ie/courses/postgraduate/",
     "known_open":None,"known_deadline":"2027-01-15",
     "tuition":"€13,500/yr (~₹12L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"High",
     "notes":"Sep 2026 CLOSED. Jan 2027 intake TBC. Has Cloud+DevOps+AI streams.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"IE03","name":"University College Dublin (UCD)","country":"Ireland","city":"Dublin","flag":"🇮🇪",
     "qs_rank":"181","qs_num":181,
     "program":"MSc CS / MSc Data Science / MSc Cybersecurity",
     "stream":"CS · Data · Cyber","check_url":"https://www.ucd.ie/cs/study/graduateprogrammes/",
     "known_open":"2025-10-01","known_deadline":"2026-07-01",
     "tuition":"€21,400/yr (~₹19L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"Medium-High",
     "notes":"QS #181. Dublin tech hub. Jul 1 non-EU deadline urgent.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"IE04","name":"University College Cork (UCC)","country":"Ireland","city":"Cork","flag":"🇮🇪",
     "qs_rank":"301-350","qs_num":325,
     "program":"MSc CS / MSc AI / MSc Software Dev",
     "stream":"AI · CS · Software","check_url":"https://www.ucc.ie/en/ckcs07/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"€14,500/yr (~₹13L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"High",
     "notes":"Affordable. Apple HQ in Cork. 60% minimum.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"IE07","name":"Trinity College Dublin","country":"Ireland","city":"Dublin","flag":"🇮🇪",
     "qs_rank":"81","qs_num":81,
     "program":"MSc CS / MSc AI",
     "stream":"AI · CS","check_url":"https://www.tcd.ie/courses/postgraduate/az/course.php?id=DPECS-CSIN-1F09",
     "known_open":"2025-10-01","known_deadline":"2026-06-30",
     "tuition":"€26,620/yr (~₹24L)","language":"TOEFL 100 / IELTS 7.0",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"Reach",
     "notes":"QS #81. Deadline June 30 — very soon. Higher language bar (TOEFL 100).",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL 100"]},

    {"id":"IE05","name":"Maynooth University","country":"Ireland","city":"Maynooth","flag":"🇮🇪",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://www.maynoothuniversity.ie/faculty-science-engineering/",
     "known_open":"2025-10-01","known_deadline":"2026-08-31",
     "tuition":"€14,000/yr (~₹13L)","language":"TOEFL 88 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"High",
     "notes":"Very accessible. 30min from Dublin. Good safety Ireland option.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"IE06","name":"University of Limerick","country":"Ireland","city":"Limerick","flag":"🇮🇪",
     "qs_rank":"501-550","qs_num":525,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://www.ul.ie/gps/courses/",
     "known_open":"2025-10-01","known_deadline":"2026-07-31",
     "tuition":"€13,000/yr (~₹12L)","language":"TOEFL 88 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"2yr Irish Graduate visa","chance":"High",
     "notes":"Affordable. Strong industry co-op program. Apple/Dell nearby.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇩🇪  GERMANY + 🇦🇹  AUSTRIA  (8 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"DE01","name":"Universität Duisburg-Essen","country":"Germany","city":"Essen","flag":"🇩🇪",
     "qs_rank":"551-600","qs_num":575,
     "program":"MSc Computer Engineering / MSc IT / MSc Software Engineering",
     "stream":"Cloud · DevOps · Software","check_url":"https://www.uni-due.de/international/",
     "known_open":"2026-05-01","known_deadline":"2026-07-31",
     "tuition":"€350/semester (~₹32K/sem)","language":"TOEFL 85 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":True,"police":False,"medical":False,
     "post_study":"18mo German job-seeker visa","chance":"High",
     "notes":"Near-free tuition. APS required — start aps-india.de NOW. 18-month EU work visa.",
     "docs":["Passport","Transcript","APS","TOEFL","MOI","CV","SOP"]},

    {"id":"DE02","name":"TU Braunschweig","country":"Germany","city":"Braunschweig","flag":"🇩🇪",
     "qs_rank":"551-600","qs_num":575,
     "program":"MSc CS / MSc IT / MSc Software Engineering",
     "stream":"CS · Software · IT","check_url":"https://www.tu-braunschweig.de/en/studying/degree-programmes/master",
     "known_open":"2026-05-01","known_deadline":"2026-07-15",
     "tuition":"€350/semester","language":"TOEFL 85 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":True,"police":False,"medical":False,
     "post_study":"18mo German job-seeker visa","chance":"Medium-High",
     "notes":"Near-free. APS needed. Jul 15 deadline — urgent if TOEFL arrives soon.",
     "docs":["Passport","Transcript","APS","TOEFL","CV","SOP"]},

    {"id":"DE03","name":"Universität Stuttgart","country":"Germany","city":"Stuttgart","flag":"🇩🇪",
     "qs_rank":"301-350","qs_num":325,
     "program":"MSc CS / MSc IT / MSc Machine Learning (INFOTECH)",
     "stream":"ML · AI · CS","check_url":"https://www.uni-stuttgart.de/en/study/",
     "known_open":"2026-05-01","known_deadline":"2026-07-15",
     "tuition":"€350/semester","language":"TOEFL 85 / IELTS 6.0",
     "gpa_min_pct":65,"toefl":True,"aps":True,"police":False,"medical":False,
     "post_study":"18mo German job-seeker visa","chance":"Medium-High",
     "notes":"INFOTECH — top ML program in Germany. APS + TOEFL needed.",
     "docs":["Passport","Transcript","APS","TOEFL","CV","SOP"]},

    {"id":"DE04","name":"Hochschule Bonn-Rhein-Sieg","country":"Germany","city":"Sankt Augustin","flag":"🇩🇪",
     "qs_rank":"unranked","qs_num":9999,
     "program":"MSc Autonomous Systems / MSc CS / MSc AI",
     "stream":"AI · CS · Autonomous","check_url":"https://www.h-brs.de/en/studying/master",
     "known_open":"2026-05-01","known_deadline":"2026-07-31",
     "tuition":"€350/semester","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":True,"police":False,"medical":False,
     "post_study":"18mo German job-seeker visa","chance":"High",
     "notes":"Applied sciences uni. Lower bar. Near Bonn/Cologne.",
     "docs":["Passport","Transcript","APS","TOEFL","CV","SOP"]},

    {"id":"DE05","name":"Hochschule Rhein-Waal","country":"Germany","city":"Kleve","flag":"🇩🇪",
     "qs_rank":"unranked","qs_num":9999,
     "program":"MSc CS / MSc IT / MSc Digital Technologies",
     "stream":"CS · IT · Digital","check_url":"https://www.hochschule-rhein-waal.de/en/studies",
     "known_open":"2026-05-01","known_deadline":"2026-07-31",
     "tuition":"€350/semester","language":"TOEFL 79 / IELTS 5.5",
     "gpa_min_pct":50,"toefl":True,"aps":True,"police":False,"medical":False,
     "post_study":"18mo German job-seeker visa","chance":"High",
     "notes":"Lowest language bar on Germany list. Near Netherlands border.",
     "docs":["Passport","Transcript","APS","TOEFL","CV","SOP"]},

    {"id":"AT01","name":"TU Wien","country":"Austria","city":"Vienna","flag":"🇦🇹",
     "qs_rank":"151-200","qs_num":175,
     "program":"MSc CS / MSc Data Engineering / MSc Logic & Computation",
     "stream":"CS · Data · AI","check_url":"https://www.tuwien.at/en/studies/programs",
     "known_open":"2026-03-01","known_deadline":"2026-07-15",
     "tuition":"€1,500/semester (~₹1.4L/sem)","language":"TOEFL 87 / Duolingo 115+",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"No APS needed. QS #151. Vienna = world's most livable city.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"AT02","name":"JKU Linz","country":"Austria","city":"Linz","flag":"🇦🇹",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.jku.at/en/studying/study-programs/master-programs/",
     "known_open":"2026-03-01","known_deadline":"2026-09-01",
     "tuition":"€1,500/semester","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"No APS. Linz — Austria's tech hub.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"AT03","name":"University of Vienna","country":"Austria","city":"Vienna","flag":"🇦🇹",
     "qs_rank":"150","qs_num":150,
     "program":"MSc CS / MSc Data Science / MSc Computational Science",
     "stream":"CS · Data · AI","check_url":"https://www.univie.ac.at/en/studying/",
     "known_open":"2026-03-01","known_deadline":"2026-09-01",
     "tuition":"€1,500/semester","language":"TOEFL 87 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"No APS. QS #150. Vienna. Strong research university.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    # ══════════════════════════════════════════════════════════
    # 🇫🇮  FINLAND  (4 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"FI01","name":"Aalto University","country":"Finland","city":"Espoo","flag":"🇫🇮",
     "qs_rank":"109","qs_num":109,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.aalto.fi/en/admissions/",
     "known_open":"2025-12-01","known_deadline":"2026-01-15",
     "tuition":"€15,000/yr (~₹14L)","language":"TOEFL 92 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"Jan deadline passed. Sep 2027 cycle opens Dec 2026. Nokia/Rovio HQ nearby.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"FI02","name":"University of Helsinki","country":"Finland","city":"Helsinki","flag":"🇫🇮",
     "qs_rank":"107","qs_num":107,
     "program":"MSc CS / MSc Data Science / MSc Software Systems",
     "stream":"CS · Data · Software","check_url":"https://www.helsinki.fi/en/admissions/",
     "known_open":"2025-12-01","known_deadline":"2026-01-22",
     "tuition":"€18,000/yr (~₹16L)","language":"TOEFL 92 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"Jan deadline passed. Sep 2027 cycle opens Dec 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"FI03","name":"University of Oulu","country":"Finland","city":"Oulu","flag":"🇫🇮",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc CS / MSc Software / MSc AI",
     "stream":"CS · Software · AI","check_url":"https://www.oulu.fi/en/admissions",
     "known_open":"2025-12-01","known_deadline":"2026-01-22",
     "tuition":"€10,000/yr (~₹9L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"5G research hub. Nokia connection. Sep 2027 cycle.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"FI04","name":"Tampere University","country":"Finland","city":"Tampere","flag":"🇫🇮",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc CS / MSc Software Engineering / MSc Data Engineering",
     "stream":"CS · Software · Data","check_url":"https://www.tuni.fi/en/study-with-us",
     "known_open":"2025-12-01","known_deadline":"2026-01-22",
     "tuition":"€12,000/yr (~₹11L)","language":"TOEFL 92 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"Strong software engineering research. Sep 2027 cycle.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    # ══════════════════════════════════════════════════════════
    # 🇮🇹  ITALY  (4 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"IT01","name":"Politecnico di Milano","country":"Italy","city":"Milan","flag":"🇮🇹",
     "qs_rank":"139","qs_num":139,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.polimi.it/en/programmes/laurea-magistrale/",
     "known_open":"2026-02-01","known_deadline":"2026-07-31",
     "tuition":"€3,900/yr (~₹3.5L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"QS #139 — top Italian uni. Very affordable. Apply NOW — Jul 31.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"IT02","name":"Politecnico di Torino","country":"Italy","city":"Turin","flag":"🇮🇹",
     "qs_rank":"301-350","qs_num":325,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.polito.it/en/education/master-of-science/",
     "known_open":"2026-02-01","known_deadline":"2026-07-31",
     "tuition":"€3,700/yr (~₹3.3L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Very affordable. Turin = automotive AI hub.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"IT03","name":"University of Bologna","country":"Italy","city":"Bologna","flag":"🇮🇹",
     "qs_rank":"154","qs_num":154,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://www.unibo.it/en/study/",
     "known_open":"2026-02-01","known_deadline":"2026-07-31",
     "tuition":"€2,900/yr (~₹2.6L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Oldest university in the world. QS #154. Cheapest top-200 EU option.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"IT04","name":"University of Trento","country":"Italy","city":"Trento","flag":"🇮🇹",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://www.unitn.it/en/apply",
     "known_open":"2026-03-01","known_deadline":"2026-08-31",
     "tuition":"€2,500/yr (~₹2.3L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Strong AI research. Microsoft Research Europe partnership. Very affordable.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    # ══════════════════════════════════════════════════════════
    # 🇪🇺  EUROPE — Czech, Estonia, Netherlands, Sweden
    # ══════════════════════════════════════════════════════════
    {"id":"CZ01","name":"Charles University Prague","country":"Czech Republic","city":"Prague","flag":"🇨🇿",
     "qs_rank":"281","qs_num":281,
     "program":"MSc CS / MSc Software Engineering / MSc AI",
     "stream":"CS · AI · Software","check_url":"https://www.cuni.cz/UKEN-178.html",
     "known_open":"2026-11-01","known_deadline":"2027-04-30",
     "tuition":"€4,000/yr (~₹3.5L)","language":"TOEFL 80 / MOI",
     "gpa_min_pct":60,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"QS #281. Prague = Europe's best student city. Feb 2027 intake.",
     "docs":["Passport","Transcript","MOI/TOEFL","CV","PS"]},

    {"id":"CZ02","name":"Czech Technical University (CTU)","country":"Czech Republic","city":"Prague","flag":"🇨🇿",
     "qs_rank":"551-600","qs_num":575,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://www.cvut.cz/en/studying",
     "known_open":"2026-11-01","known_deadline":"2027-04-30",
     "tuition":"€3,500/yr (~₹3.2L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Engineering-focused. Lower bar than Charles.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"EE01","name":"TalTech — Tallinn University of Technology","country":"Estonia","city":"Tallinn","flag":"🇪🇪",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc IT / MSc Cybersecurity / MSc Data Science",
     "stream":"CS · Cyber · Data","check_url":"https://taltech.ee/en/admission/masters-studies",
     "known_open":"2027-02-01","known_deadline":"2027-05-01",
     "tuition":"€3,200/yr (~₹3L)","language":"TOEFL 79 / MOI / IELTS 6.0",
     "gpa_min_pct":60,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Best value EU degree. Tallinn = Skype HQ. Feb 2027 intake opens Feb 1, 2027.",
     "docs":["Passport","Transcript","MOI","CV","PS","GRE"]},

    {"id":"NL01","name":"University of Twente","country":"Netherlands","city":"Enschede","flag":"🇳🇱",
     "qs_rank":"163","qs_num":163,
     "program":"MSc CS / MSc Data Science / MSc Embedded Systems",
     "stream":"CS · Data · Embedded","check_url":"https://www.utwente.nl/en/education/master/",
     "known_open":"2025-10-01","known_deadline":"2026-05-01",
     "tuition":"€18,200/yr (~₹16L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"Techno-entrepreneurial campus. Check if late applications accepted.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"NL02","name":"Eindhoven University of Technology (TU/e)","country":"Netherlands","city":"Eindhoven","flag":"🇳🇱",
     "qs_rank":"131","qs_num":131,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Technology",
     "stream":"AI · CS · Software","check_url":"https://www.tue.nl/en/education/graduate-school/masters-programs/",
     "known_open":"2025-10-01","known_deadline":"2026-04-01",
     "tuition":"€2,209/yr EU / €16,000/yr non-EU (~₹14L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"QS #131. April deadline likely passed — check for late admissions. ASML, Philips HQs nearby.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"SE01","name":"KTH Royal Institute of Technology","country":"Sweden","city":"Stockholm","flag":"🇸🇪",
     "qs_rank":"97","qs_num":97,
     "program":"MSc CS / MSc Data Science / MSc Machine Learning",
     "stream":"ML · CS · Data","check_url":"https://www.kth.se/en/studies/master/",
     "known_open":"2025-10-15","known_deadline":"2026-01-15",
     "tuition":"~SEK 310,000/yr (~₹25L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":70,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"QS #97. Jan deadline passed. Sep 2027 cycle opens Oct 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"SE02","name":"Chalmers University of Technology","country":"Sweden","city":"Gothenburg","flag":"🇸🇪",
     "qs_rank":"201-250","qs_num":225,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.chalmers.se/en/education/",
     "known_open":"2025-10-15","known_deadline":"2026-01-15",
     "tuition":"~SEK 310,000/yr (~₹25L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":70,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"Jan deadline passed. Sep 2027 cycle opens Oct 2026. Strong Volvo/Ericsson partnerships.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    # ══════════════════════════════════════════════════════════
    # 🇯🇵  JAPAN  (11 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"JP01","name":"JAIST","country":"Japan","city":"Nomi, Ishikawa","flag":"🇯🇵",
     "qs_rank":"Top 15 Japan research","qs_num":500,
     "program":"MSc Information Science / MSc AI / MSc Software / MSc Knowledge Science",
     "stream":"AI · Software · CS","check_url":"https://www.jaist.ac.jp/english/admissions/",
     "known_open":"2026-09-04","known_deadline":"2026-09-16",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 79+ / MOI",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"High",
     "notes":"Apr 2027 intake — Second Round Sep 4–16, 2026. Online exam only — no travel.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL/MOI"]},

    {"id":"JP02","name":"University of Tsukuba","country":"Japan","city":"Tsukuba","flag":"🇯🇵",
     "qs_rank":"328","qs_num":328,
     "program":"MSc CS / MSc Systems & Information Engineering",
     "stream":"CS · AI · Systems","check_url":"https://www.cs.tsukuba.ac.jp/english/admission.html",
     "known_open":None,"known_deadline":"2026-10-31",
     "tuition":"~¥535,800/yr (~₹3L)","language":"MOI accepted",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"Target: Prof Fumio Machida (AIOps). Email query-gint@cs.tsukuba.ac.jp.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","MOI"]},

    {"id":"JP03","name":"University of Tokyo","country":"Japan","city":"Tokyo","flag":"🇯🇵",
     "qs_rank":"28","qs_num":28,
     "program":"MSc CS / MSc AI / MSc Information Science",
     "stream":"AI · CS · Research","check_url":"https://www.i.u-tokyo.ac.jp/edu/course/mi/admission.shtml",
     "known_open":"2026-09-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 80 / Duolingo 115+",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Reach",
     "notes":"QS #28. MUST contact professor first. Your papers relevant to CS labs here.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL","Professor agreement"]},

    {"id":"JP04","name":"Osaka University","country":"Japan","city":"Osaka","flag":"🇯🇵",
     "qs_rank":"68","qs_num":68,
     "program":"MSc CS / MSc AI / MSc Information Science",
     "stream":"AI · CS","check_url":"https://www.ist.osaka-u.ac.jp/english/admission/",
     "known_open":"2026-09-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"QS #68. Spring intake. Contact supervisor now.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP05","name":"Nagoya University","country":"Japan","city":"Nagoya","flag":"🇯🇵",
     "qs_rank":"118","qs_num":118,
     "program":"MSc CS / MSc AI / MSc Informatics",
     "stream":"AI · CS","check_url":"https://www.i.nagoya-u.ac.jp/en/graduate/admission/",
     "known_open":"2026-09-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"Toyota Group nearby = industry access. Contact supervisor Sept 2026.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP06","name":"Tohoku University","country":"Japan","city":"Sendai","flag":"🇯🇵",
     "qs_rank":"208","qs_num":208,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://www.tohoku.ac.jp/en/admissions/graduate.html",
     "known_open":"2026-09-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"Sendai — affordable Japanese city.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP07","name":"Kyushu University","country":"Japan","city":"Fukuoka","flag":"🇯🇵",
     "qs_rank":"271","qs_num":271,
     "program":"MSc CS / MSc AI / MSc Information Science",
     "stream":"CS · AI","check_url":"https://www.kyushu-u.ac.jp/en/faculties/iii/admission/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"High",
     "notes":"Target: Prof Yasutaka Kamei (MSR/software analytics). Fukuoka = startup hub.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP08","name":"Ritsumeikan University","country":"Japan","city":"Kyoto","flag":"🇯🇵",
     "qs_rank":"501-550","qs_num":525,
     "program":"MSc CS / MSc AI / MSc Information Systems",
     "stream":"CS · AI","check_url":"https://en.ritsumei.ac.jp/gsise/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"~¥700,000/yr (~₹4L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"High",
     "notes":"Private uni — easier admission than national unis. Kyoto location.",
     "docs":["Passport","Transcript","CV","2 LORs","TOEFL"]},

    {"id":"JP09","name":"Keio University","country":"Japan","city":"Tokyo","flag":"🇯🇵",
     "qs_rank":"189","qs_num":189,
     "program":"MSc CS / MSc AI / MSc Information Engineering",
     "stream":"CS · AI","check_url":"https://www.st.keio.ac.jp/en/admissions/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"~¥700,000/yr (~₹4L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"Private. Tokyo. Sony/Fujitsu recruit here.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP10","name":"Waseda University","country":"Japan","city":"Tokyo","flag":"🇯🇵",
     "qs_rank":"197","qs_num":197,
     "program":"MSc CS / MSc AI / MSc Information Networks",
     "stream":"CS · AI · Networks","check_url":"https://www.waseda.jp/fsci/en/admissions/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"~¥700,000/yr (~₹4L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"Medium-High",
     "notes":"Private. Tokyo. Your Japanese coursework = advantage.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    {"id":"JP11","name":"Hokkaido University","country":"Japan","city":"Sapporo","flag":"🇯🇵",
     "qs_rank":"290","qs_num":290,
     "program":"MSc CS / MSc AI / MSc Information Science",
     "stream":"CS · AI","check_url":"https://www.hokudai.ac.jp/en/admission/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"~¥535,800/yr (~₹3L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HSP-J visa","chance":"High",
     "notes":"National uni. Sapporo — great quality of life, lower competition than Tokyo.",
     "docs":["Passport","Transcript","Research Plan","CV","2 LORs","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇭🇰  HONG KONG  (5 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"HK01","name":"HKU","country":"Hong Kong","city":"Hong Kong","flag":"🇭🇰",
     "qs_rank":"17","qs_num":17,
     "program":"MSc CS — Cybersecurity / AI & Web3 / Financial Computing",
     "stream":"AI · Cyber · CS","check_url":"https://tpgadmission.cds.hku.hk",
     "known_open":"2026-06-01","known_deadline":"2026-08-31",
     "tuition":"HKD 135,000/yr (~₹15L)","language":"TOEFL 80 / MOI",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"HK Immigration","chance":"Reach",
     "notes":"All MSc CS showed CLOSED. Monitor for 2027-28 opening.",
     "docs":["Passport","Transcript","CV","PS","MOI/TOEFL"]},

    {"id":"HK02","name":"HKUST","country":"Hong Kong","city":"Hong Kong","flag":"🇭🇰",
     "qs_rank":"47","qs_num":47,
     "program":"MSc CS & Engineering / MSc Big Data Technology",
     "stream":"CS · AI · Data","check_url":"https://fytgs.hkust.edu.hk/admissions",
     "known_open":"2026-09-01","known_deadline":"2026-12-31",
     "tuition":"HKD 130,000/yr (~₹14L)","language":"TOEFL 80 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HK Immigration","chance":"Reach",
     "notes":"QS #47. Fall 2027 intake opens Sep 2026.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"HK03","name":"CUHK","country":"Hong Kong","city":"Hong Kong","flag":"🇭🇰",
     "qs_rank":"36","qs_num":36,
     "program":"MSc CS / MSc AI / MSc Information Engineering",
     "stream":"AI · CS","check_url":"https://www.cse.cuhk.edu.hk/en/education/postgraduate-programmes",
     "known_open":"2026-09-01","known_deadline":"2026-12-01",
     "tuition":"HKD 120,000/yr (~₹13L)","language":"TOEFL 79 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HK Immigration","chance":"Reach",
     "notes":"QS #36. Sep 2027 intake opens Sep 2026.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","TOEFL"]},

    {"id":"HK04","name":"PolyU","country":"Hong Kong","city":"Hong Kong","flag":"🇭🇰",
     "qs_rank":"57","qs_num":57,
     "program":"MSc Computing / MSc Data Science / MSc IT",
     "stream":"CS · Data · IT","check_url":"https://www.polyu.edu.hk/gs/prospective-students/application/",
     "known_open":"2026-07-01","known_deadline":"2026-10-31",
     "tuition":"HKD 110,000/yr (~₹12L)","language":"TOEFL 80 / MOI",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"HK Immigration","chance":"Medium-High",
     "notes":"More accessible than HKU/HKUST.",
     "docs":["Passport","Transcript","CV","PS","MOI/TOEFL"]},

    {"id":"HK05","name":"HKBU","country":"Hong Kong","city":"Hong Kong","flag":"🇭🇰",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://www.hkbu.edu.hk/admissions/",
     "known_open":"2026-07-01","known_deadline":"2026-10-31",
     "tuition":"HKD 90,000/yr (~₹10L)","language":"TOEFL 80 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"HK Immigration","chance":"Medium-High",
     "notes":"Most accessible HK university for your profile.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇦🇺  AUSTRALIA  (13 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"AU01","name":"University of Melbourne","country":"Australia","city":"Melbourne","flag":"🇦🇺",
     "qs_rank":"19","qs_num":19,
     "program":"Master of IT / Master of CS / Master of Data Science",
     "stream":"CS · Data · IT","check_url":"https://study.unimelb.edu.au/find/courses/graduate/master-of-information-technology/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 45,000/yr (~₹25L)","language":"TOEFL 79 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"Medium-High",
     "notes":"QS #19. CGPA 7.0 inside their 65–75% range. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU02","name":"University of Sydney","country":"Australia","city":"Sydney","flag":"🇦🇺",
     "qs_rank":"18","qs_num":18,
     "program":"MSc CS / MSc Data Science / MSc IT",
     "stream":"CS · Data · IT","check_url":"https://www.sydney.edu.au/courses/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 46,500/yr (~₹26L)","language":"TOEFL 85 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"Medium-High",
     "notes":"QS #18. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU03","name":"UNSW Sydney","country":"Australia","city":"Sydney","flag":"🇦🇺",
     "qs_rank":"19","qs_num":19,
     "program":"Master of IT / MSc CS / MSc AI",
     "stream":"CS · AI · IT","check_url":"https://www.unsw.edu.au/study/postgraduate/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 43,000/yr (~₹24L)","language":"TOEFL 85 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"Medium-High",
     "notes":"QS #19. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU04","name":"Monash University","country":"Australia","city":"Melbourne","flag":"🇦🇺",
     "qs_rank":"57","qs_num":57,
     "program":"MSc CS / MSc Data Science / MSc AI",
     "stream":"CS · Data · AI","check_url":"https://www.monash.edu/study/courses/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 40,000/yr (~₹22L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"Medium-High",
     "notes":"QS #57. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU05","name":"University of Queensland (UQ)","country":"Australia","city":"Brisbane","flag":"🇦🇺",
     "qs_rank":"40","qs_num":40,
     "program":"MSc CS / MSc Data Science / MSc Software Engineering",
     "stream":"CS · Data · Software","check_url":"https://study.uq.edu.au/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 44,000/yr (~₹24L)","language":"TOEFL 87 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"Medium",
     "notes":"QS #40. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU06","name":"RMIT University","country":"Australia","city":"Melbourne","flag":"🇦🇺",
     "qs_rank":"121","qs_num":121,
     "program":"MSc IT / MSc AI / MSc Data Science / MSc Cloud & Cybersecurity",
     "stream":"Cloud · AI · Data · IT","check_url":"https://www.rmit.edu.au/study-with-us/levels-of-study/postgraduate-study/masters",
     "known_open":"2026-01-01","known_deadline":"2027-02-28",
     "tuition":"AUD 38,000/yr (~₹21L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":50,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Lowest GPA bar (2.0/4.0). Rolling admissions.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU07","name":"University of Adelaide","country":"Australia","city":"Adelaide","flag":"🇦🇺",
     "qs_rank":"89","qs_num":89,
     "program":"Master of IT / MSc CS / MSc Data Science",
     "stream":"CS · Data · IT","check_url":"https://www.adelaide.edu.au/degree-finder/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 38,000/yr (~₹21L)","language":"TOEFL 79 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-4yr","chance":"High",
     "notes":"QS #89. Adelaide cheaper than Sydney/Melbourne. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"AU08","name":"Deakin University","country":"Australia","city":"Melbourne","flag":"🇦🇺",
     "qs_rank":"321","qs_num":321,
     "program":"MSc IT / MSc AI / MSc CS / MSc Cybersecurity",
     "stream":"AI · Cyber · IT","check_url":"https://www.deakin.edu.au/course/master-information-technology",
     "known_open":"2026-01-01","known_deadline":"2027-02-28",
     "tuition":"AUD 33,000/yr (~₹18L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Rolling admissions. Cybersecurity MSc relevant to your papers.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU09","name":"Macquarie University","country":"Australia","city":"Sydney","flag":"🇦🇺",
     "qs_rank":"195","qs_num":195,
     "program":"MSc IT / MSc AI / MSc Data Science / MSc Cybersecurity",
     "stream":"AI · Data · Cyber","check_url":"https://www.mq.edu.au/study/find-a-course/postgraduate",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 36,000/yr (~₹20L)","language":"TOEFL 79 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Sydney location. Rolling admissions.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU10","name":"Curtin University","country":"Australia","city":"Perth","flag":"🇦🇺",
     "qs_rank":"233","qs_num":233,
     "program":"MSc IT / MSc CS / MSc Data Science / MSc Cybersecurity",
     "stream":"CS · Data · Cyber","check_url":"https://study.curtin.edu.au/",
     "known_open":"2026-01-01","known_deadline":"2027-02-28",
     "tuition":"AUD 32,000/yr (~₹18L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Perth — cheapest Australian city. Rolling admissions.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU11","name":"Griffith University","country":"Australia","city":"Brisbane","flag":"🇦🇺",
     "qs_rank":"381-390","qs_num":385,
     "program":"MSc IT / MSc CS / MSc Data Science",
     "stream":"CS · Data · IT","check_url":"https://www.griffith.edu.au/study/postgraduate",
     "known_open":"2026-01-01","known_deadline":"2027-02-28",
     "tuition":"AUD 28,000/yr (~₹15L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":50,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Affordable. Rolling admissions. Brisbane 2032 Olympics tech investment.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU12","name":"La Trobe University","country":"Australia","city":"Melbourne","flag":"🇦🇺",
     "qs_rank":"401-450","qs_num":425,
     "program":"MSc IT / MSc CS / MSc Data Science",
     "stream":"CS · Data · IT","check_url":"https://www.latrobe.edu.au/courses/master-of-information-technology",
     "known_open":"2026-01-01","known_deadline":"2027-02-28",
     "tuition":"AUD 29,000/yr (~₹16L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":50,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Affordable Melbourne option. Low bar. Rolling admissions.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    {"id":"AU13","name":"University of Technology Sydney (UTS)","country":"Australia","city":"Sydney","flag":"🇦🇺",
     "qs_rank":"133","qs_num":133,
     "program":"Master of IT / MSc CS / MSc Data Science / MSc AI",
     "stream":"AI · Data · IT","check_url":"https://www.uts.edu.au/study/find-a-course/",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"AUD 40,000/yr (~₹22L)","language":"TOEFL 79 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"485 visa 2-3yr","chance":"High",
     "notes":"Sydney location. Strong industry partnerships. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇳🇿  NEW ZEALAND  (3 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"NZ01","name":"Victoria University of Wellington","country":"New Zealand","city":"Wellington","flag":"🇳🇿",
     "qs_rank":"244","qs_num":244,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.wgtn.ac.nz/postgraduate/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"NZD 35,000/yr (~₹18L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr open work visa","chance":"High",
     "notes":"3-year post-study work visa — most generous globally. Feb 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"NZ02","name":"University of Canterbury","country":"New Zealand","city":"Christchurch","flag":"🇳🇿",
     "qs_rank":"254","qs_num":254,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://www.canterbury.ac.nz/study/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"NZD 32,000/yr (~₹16L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr open work visa","chance":"High",
     "notes":"Strong CS. Christchurch — rebuilt modern city.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    {"id":"NZ03","name":"AUT — Auckland University of Technology","country":"New Zealand","city":"Auckland","flag":"🇳🇿",
     "qs_rank":"416-450","qs_num":430,
     "program":"MSc CS / MSc IT / MSc Data Science",
     "stream":"CS · IT · Data","check_url":"https://www.aut.ac.nz/study/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"NZD 30,000/yr (~₹16L)","language":"TOEFL 90 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr open work visa","chance":"High",
     "notes":"More accessible than University of Auckland. 3yr visa.",
     "docs":["Passport","Transcript","CV","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇸🇬  SINGAPORE  (4 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"SG01","name":"NUS — National University of Singapore","country":"Singapore","city":"Singapore","flag":"🇸🇬",
     "qs_rank":"8","qs_num":8,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.comp.nus.edu.sg/programmes/pg/mcs/",
     "known_open":"2026-08-01","known_deadline":"2026-11-30",
     "tuition":"SGD 45,000 (~₹28L)","language":"TOEFL 85 / MOI waiver",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"LOC/EP Singapore","chance":"Reach",
     "notes":"QS #8 globally. GRE 324 above benchmark. MOI waiver possible. Jan 2027 intake.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","GRE","TOEFL/MOI"]},

    {"id":"SG02","name":"NTU — Nanyang Technological University","country":"Singapore","city":"Singapore","flag":"🇸🇬",
     "qs_rank":"26","qs_num":26,
     "program":"MSc AI / MSc Data Science / MSc CS",
     "stream":"AI · Data · CS","check_url":"https://www.ntu.edu.sg/admissions/graduate",
     "known_open":"2026-10-01","known_deadline":"2026-11-30",
     "tuition":"SGD 38,000 (~₹24L)","language":"TOEFL 90 / MOI waiver",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"LOC/EP Singapore","chance":"Reach",
     "notes":"QS #26. Jan 2027 intake opens Oct 2026. GRE 324 > 315 benchmark.",
     "docs":["Passport","Transcript","CV","PS","2 LORs","GRE","TOEFL/MOI"]},

    {"id":"SG03","name":"SMU — Singapore Management University","country":"Singapore","city":"Singapore","flag":"🇸🇬",
     "qs_rank":"585","qs_num":585,
     "program":"MSc Computing — Software / AI / Data",
     "stream":"AI · Software · Data","check_url":"https://scis.smu.edu.sg/master-science-computing",
     "known_open":"2026-05-01","known_deadline":"2026-09-30",
     "tuition":"SGD 40,000 (~₹25L)","language":"TOEFL 90 / MOI waiver",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"LOC/EP Singapore","chance":"Medium",
     "notes":"Sep 30 deadline. Target: Prof David Lo (software analytics).",
     "docs":["Passport","Transcript","CV","Essays","2 LORs","GRE","TOEFL/MOI"]},

    {"id":"SG04","name":"SIT — Singapore Institute of Technology","country":"Singapore","city":"Singapore","flag":"🇸🇬",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc IT / MSc CS / MSc Software Engineering",
     "stream":"Software · IT · CS","check_url":"https://www.singaporetech.edu.sg/admissions/postgraduate",
     "known_open":"2026-07-01","known_deadline":"2026-11-30",
     "tuition":"SGD 25,000 (~₹16L)","language":"TOEFL 85 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"LOC/EP Singapore","chance":"Medium-High",
     "notes":"More accessible than NUS/NTU. Industry-focused. Lower tuition.",
     "docs":["Passport","Transcript","CV","PS","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇨🇦  CANADA  (5 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"CA01","name":"Memorial University of Newfoundland","country":"Canada","city":"St. John's","flag":"🇨🇦",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc Software Engineering",
     "stream":"CS · Software","check_url":"https://www.mun.ca/computerscience/graduate/",
     "known_open":"2026-10-01","known_deadline":"2027-02-28",
     "tuition":"CAD 12,000/yr (~₹7L)","language":"TOEFL 80 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr PGWP → PR","chance":"High",
     "notes":"Canada's cheapest. 3-year PGWP. Fall 2027 intake.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","TOEFL"]},

    {"id":"CA02","name":"University of New Brunswick","country":"Canada","city":"Fredericton","flag":"🇨🇦",
     "qs_rank":"601-650","qs_num":625,
     "program":"MSc CS / MSc Software Engineering",
     "stream":"CS · Software","check_url":"https://www.unb.ca/academics/calendar/graduate/",
     "known_open":"2026-10-01","known_deadline":"2027-03-01",
     "tuition":"CAD 15,000/yr (~₹9L)","language":"TOEFL 80 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr PGWP → PR","chance":"High",
     "notes":"Affordable. 3yr PGWP. Cybersecurity research cluster.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","TOEFL"]},

    {"id":"CA03","name":"University of Lethbridge","country":"Canada","city":"Lethbridge","flag":"🇨🇦",
     "qs_rank":"701-750","qs_num":725,
     "program":"MSc CS / MSc Data Science",
     "stream":"CS · Data","check_url":"https://www.ulethbridge.ca/future-student/graduate/",
     "known_open":"2026-10-01","known_deadline":"2027-03-01",
     "tuition":"CAD 12,000/yr (~₹7L)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr PGWP → PR","chance":"High",
     "notes":"Affordable Alberta. Easy GPA bar. Good safety Canada.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","TOEFL"]},

    {"id":"CA04","name":"Concordia University","country":"Canada","city":"Montreal","flag":"🇨🇦",
     "qs_rank":"521-530","qs_num":525,
     "program":"MSc CS / MSc Data Science / MSc Software Engineering",
     "stream":"CS · Data · Software","check_url":"https://www.concordia.ca/ginacody/",
     "known_open":"2026-09-01","known_deadline":"2027-02-01",
     "tuition":"CAD 18,000/yr (~₹11L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr PGWP → PR","chance":"Medium-High",
     "notes":"Montreal — affordable bilingual city. AI/gaming hub. Fall 2027.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","TOEFL"]},

    {"id":"CA05","name":"Dalhousie University","country":"Canada","city":"Halifax","flag":"🇨🇦",
     "qs_rank":"301-350","qs_num":325,
     "program":"MACS — Master of Applied Computer Science",
     "stream":"CS · Software · AI","check_url":"https://www.dal.ca/faculty/computerscience/grad/macs.html",
     "known_open":"2026-10-01","known_deadline":"2027-04-01",
     "tuition":"CAD 20,722/yr (~₹12L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":70,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"3yr PGWP → PR","chance":"Medium",
     "notes":"16-month program with internship option. Fall 2027.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇨🇳  CHINA  (10 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"CN01","name":"Zhejiang University","country":"China","city":"Hangzhou","flag":"🇨🇳",
     "qs_rank":"65","qs_num":65,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://iczu.zju.edu.cn/admissionsen",
     "known_open":"2026-03-01","known_deadline":"2026-08-31",
     "tuition":"CNY 30,000/yr (~₹3.5L)","language":"MOI / TOEFL 80+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"QS #65 — strongest China target. Hangzhou = Alibaba HQ. Supervisor contact required.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP","Supervisor acceptance"]},

    {"id":"CN02","name":"Wuhan University","country":"China","city":"Wuhan","flag":"🇨🇳",
     "qs_rank":"225","qs_num":225,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://gs.whu.edu.cn/en/",
     "known_open":"2026-03-01","known_deadline":"2026-06-15",
     "tuition":"CNY 30,000/yr (~₹3.5L)","language":"MOI / TOEFL 80+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Deadline passed — email gsao@whu.edu.cn to check rolling. No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN03","name":"Huazhong University of Science and Technology (HUST)","country":"China","city":"Wuhan","flag":"🇨🇳",
     "qs_rank":"275","qs_num":275,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://oec.hust.edu.cn/",
     "known_open":"2026-03-01","known_deadline":"2026-07-31",
     "tuition":"CNY 28,000/yr (~₹3.3L)","language":"MOI / TOEFL 79+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"QS #275. Wuhan. Huawei research campus nearby. No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN04","name":"Sun Yat-sen University (SYSU)","country":"China","city":"Guangzhou","flag":"🇨🇳",
     "qs_rank":"285","qs_num":285,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://iso.sysu.edu.cn/",
     "known_open":"2026-03-01","known_deadline":"2026-07-31",
     "tuition":"CNY 28,000/yr (~₹3.3L)","language":"MOI / TOEFL 79+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Near Shenzhen (Huawei, Tencent, DJI). No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN05","name":"Tongji University","country":"China","city":"Shanghai","flag":"🇨🇳",
     "qs_rank":"501-550","qs_num":525,
     "program":"MSc CS / MSc IT / MSc Software Engineering",
     "stream":"CS · IT · Software","check_url":"https://en.tongji.edu.cn/",
     "known_open":"2026-03-01","known_deadline":"2026-07-31",
     "tuition":"CNY 25,000/yr (~₹3L)","language":"MOI / TOEFL 79+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Shanghai location. No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN06","name":"Beijing Institute of Technology (BIT)","country":"China","city":"Beijing","flag":"🇨🇳",
     "qs_rank":"351-400","qs_num":375,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://english.bit.edu.cn/admissions/",
     "known_open":"2026-03-01","known_deadline":"2026-07-31",
     "tuition":"CNY 25,000/yr (~₹3L)","language":"MOI accepted",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Beijing. No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN07","name":"Jilin University","country":"China","city":"Changchun","flag":"🇨🇳",
     "qs_rank":"601-800","qs_num":700,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://iso.jlu.edu.cn",
     "known_open":"2026-04-01","known_deadline":"2026-07-15",
     "tuition":"CNY 20,000/yr (~₹2.3L)","language":"MOI accepted",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"No police/medical at application confirmed. Affordable.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN08","name":"Xi'an Jiaotong University","country":"China","city":"Xi'an","flag":"🇨🇳",
     "qs_rank":"428","qs_num":428,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://cie.xjtu.edu.cn/en",
     "known_open":"2026-03-01","known_deadline":"2026-06-15",
     "tuition":"CNY 28,000/yr (~₹3.3L)","language":"MOI / TOEFL 80+",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Deadline passed — email cie@mail.xjtu.edu.cn to check rolling.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP"]},

    {"id":"CN09","name":"Harbin Institute of Technology (HIT)","country":"China","city":"Harbin","flag":"🇨🇳",
     "qs_rank":"426","qs_num":426,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://hit.at0086.cn/student",
     "known_open":"2026-04-01","known_deadline":"2026-07-15",
     "tuition":"CNY 25,000/yr (~₹3L)","language":"MOI accepted",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":True,"medical":True,
     "post_study":"Chinese Student Visa","chance":"High — when docs ready",
     "notes":"Blocked by police cert + medical cert. Get both docs then submit.",
     "docs":["Passport","Transcript","MOI","CV","2 LORs","SOP","Police cert","Health cert"]},

    {"id":"CN10","name":"Ningbo University","country":"China","city":"Ningbo","flag":"🇨🇳",
     "qs_rank":"601-800","qs_num":700,
     "program":"MSc CS / MSc IT",
     "stream":"CS · IT","check_url":"https://iso.nbu.edu.cn",
     "known_open":"2026-04-01","known_deadline":"2026-07-30",
     "tuition":"CNY 18,000/yr (~₹2.1L)","language":"MOI accepted",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Chinese Student Visa","chance":"High",
     "notes":"Scholarship sometimes available. No police/medical at application.",
     "docs":["Passport","Transcript","MOI","CV","SOP"]},

    # ══════════════════════════════════════════════════════════
    # 🌏  ASIA — Malaysia, South Korea, Taiwan
    # ══════════════════════════════════════════════════════════
    {"id":"MY01","name":"Universiti Malaya (UM)","country":"Malaysia","city":"Kuala Lumpur","flag":"🇲🇾",
     "qs_rank":"65","qs_num":65,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://umapply.um.edu.my/",
     "known_open":"2026-04-01","known_deadline":"2026-09-30",
     "tuition":"MYR 12,000/yr (~₹2.3L)","language":"TOEFL 80 / IELTS 6.0 / MOI",
     "gpa_min_pct":55,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Malaysian Student Pass","chance":"High",
     "notes":"QS #65. Best value QS top-70. MOI accepted. Rolling admissions.",
     "docs":["Passport","Transcript","MOI","CV","PS"]},

    {"id":"MY02","name":"Universiti Putra Malaysia (UPM)","country":"Malaysia","city":"Kuala Lumpur","flag":"🇲🇾",
     "qs_rank":"126","qs_num":126,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://gss.upm.edu.my/",
     "known_open":"2026-04-01","known_deadline":"2026-09-30",
     "tuition":"MYR 10,000/yr (~₹1.9L)","language":"TOEFL 79 / MOI",
     "gpa_min_pct":55,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Malaysian Student Pass","chance":"High",
     "notes":"QS #126. Very affordable. MOI accepted.",
     "docs":["Passport","Transcript","MOI","CV","PS"]},

    {"id":"MY03","name":"Universiti Teknologi Malaysia (UTM)","country":"Malaysia","city":"Johor Bahru","flag":"🇲🇾",
     "qs_rank":"201-250","qs_num":225,
     "program":"MSc CS / MSc AI / MSc Software Engineering / MSc Data Science",
     "stream":"CS · AI · Software","check_url":"https://graduate.utm.my/",
     "known_open":"2026-04-01","known_deadline":"2026-09-30",
     "tuition":"MYR 9,000/yr (~₹1.7L)","language":"TOEFL 79 / MOI",
     "gpa_min_pct":55,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Malaysian Student Pass","chance":"High",
     "notes":"Near Singapore. Extremely affordable. MOI accepted. Rolling admissions.",
     "docs":["Passport","Transcript","MOI","CV","PS"]},

    {"id":"MY04","name":"Universiti Kebangsaan Malaysia (UKM)","country":"Malaysia","city":"Bangi","flag":"🇲🇾",
     "qs_rank":"331","qs_num":331,
     "program":"MSc CS / MSc AI / MSc Information Technology",
     "stream":"CS · AI · IT","check_url":"https://www.ukm.my/pejabat_sejahtera/admissions/",
     "known_open":"2026-04-01","known_deadline":"2026-09-30",
     "tuition":"MYR 8,000/yr (~₹1.5L)","language":"MOI accepted",
     "gpa_min_pct":55,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Malaysian Student Pass","chance":"High",
     "notes":"National university. Very affordable. Near KL. MOI accepted.",
     "docs":["Passport","Transcript","MOI","CV","PS"]},

    {"id":"KR01","name":"KAIST","country":"South Korea","city":"Daejeon","flag":"🇰🇷",
     "qs_rank":"62","qs_num":62,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://admission.kaist.ac.kr/intl-graduate/",
     "known_open":"2026-08-01","known_deadline":"2026-09-30",
     "tuition":"KRW 4,000,000/semester (~₹1.3L/sem)","language":"TOEFL 83 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"D-2 student visa Korea","chance":"Reach",
     "notes":"Korea's MIT. Target: Prof Shin Yoo (software analytics). Feb intake — apply Sep 2026.",
     "docs":["Passport","Transcript","CV","Research Plan","2 LORs","TOEFL"]},

    {"id":"KR02","name":"Yonsei University","country":"South Korea","city":"Seoul","flag":"🇰🇷",
     "qs_rank":"62","qs_num":62,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://graduate.yonsei.ac.kr/graduate/admission/",
     "known_open":"2026-08-01","known_deadline":"2026-10-31",
     "tuition":"KRW 8,000,000/semester (~₹2.7L/sem)","language":"TOEFL 83 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"D-2 student visa Korea","chance":"Reach",
     "notes":"Seoul. Feb 2027 intake. Samsung, LG, Hyundai recruit here.",
     "docs":["Passport","Transcript","CV","2 LORs","TOEFL"]},

    {"id":"TW01","name":"National Taiwan University (NTU)","country":"Taiwan","city":"Taipei","flag":"🇹🇼",
     "qs_rank":"65","qs_num":65,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://www.csie.ntu.edu.tw/admissions/",
     "known_open":"2026-09-01","known_deadline":"2026-12-31",
     "tuition":"TWD 60,000/semester (~₹1.6L/sem)","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"Taiwan ARC","chance":"Medium-High",
     "notes":"QS #65. TSMC, Foxconn HQ in Taiwan. Sep 2027 intake — apply Dec 2026.",
     "docs":["Passport","Transcript","CV","Research Plan","2 LORs","TOEFL"]},

    {"id":"TW02","name":"NYCU — National Yang Ming Chiao Tung University","country":"Taiwan","city":"Hsinchu","flag":"🇹🇼",
     "qs_rank":"251-300","qs_num":275,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://oia.nycu.edu.tw/",
     "known_open":"2026-09-01","known_deadline":"2026-12-31",
     "tuition":"TWD 50,000/semester (~₹1.3L/sem)","language":"TOEFL 79 / IELTS 6.0 / MOI",
     "gpa_min_pct":None,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"Taiwan ARC","chance":"High",
     "notes":"TSMC directly recruits from NYCU. Hsinchu Science Park = Silicon Valley of Asia. Strong CS faculty. MOI accepted.",
     "docs":["Passport","Transcript","CV","Research Plan","2 LORs","MOI/TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇰🇷  SOUTH KOREA — Additional (1 university)
    # ══════════════════════════════════════════════════════════
    {"id":"KR03","name":"Seoul National University (SNU)","country":"South Korea","city":"Seoul","flag":"🇰🇷",
     "qs_rank":"41","qs_num":41,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"CS · AI · Data","check_url":"https://en.snu.ac.kr/apply",
     "known_open":"2026-09-01","known_deadline":"2026-11-30",
     "tuition":"KRW 5,000,000/semester (~₹1.7L/sem)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"D-2 student visa Korea","chance":"Reach",
     "notes":"QS #41. Korea's top uni. Samsung/LG/Kakao recruit heavily. Feb 2027 intake — apply Sep–Nov 2026.",
     "docs":["Passport","Transcript","CV","Research Plan","2 LORs","TOEFL"]},

    # ══════════════════════════════════════════════════════════
    # 🇳🇱  NETHERLANDS — Additional (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"NL03","name":"TU Delft","country":"Netherlands","city":"Delft","flag":"🇳🇱",
     "qs_rank":"57","qs_num":57,
     "program":"MSc CS / MSc AI / MSc Data Science & Technology",
     "stream":"AI · CS · Data","check_url":"https://www.tudelft.nl/en/education/programmes/masters/",
     "known_open":"2026-10-01","known_deadline":"2027-04-01",
     "tuition":"€18,750/yr (~₹17L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"QS #57. Sep 2027 cycle opens Oct 2026. Shell, Philips, ASML recruit on campus.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"NL04","name":"University of Amsterdam","country":"Netherlands","city":"Amsterdam","flag":"🇳🇱",
     "qs_rank":"53","qs_num":53,
     "program":"MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"AI · Data · Software","check_url":"https://www.uva.nl/en/programmes/masters/",
     "known_open":"2026-10-01","known_deadline":"2027-04-15",
     "tuition":"€18,900/yr (~₹17L)","language":"TOEFL 92 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Reach",
     "notes":"QS #53. Booking.com, Adyen, Uber Europe HQ in Amsterdam. Sep 2027 cycle opens Oct 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    # ══════════════════════════════════════════════════════════
    # 🇧🇪  BELGIUM  (3 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"BE01","name":"KU Leuven","country":"Belgium","city":"Leuven","flag":"🇧🇪",
     "qs_rank":"67","qs_num":67,
     "program":"MSc AI / MSc CS / MSc Cybersecurity / MSc Data Science",
     "stream":"AI · CS · Cyber","check_url":"https://www.kuleuven.be/english/admissions/",
     "known_open":"2026-10-01","known_deadline":"2027-02-01",
     "tuition":"€7,200/yr (~₹6.5L)","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"QS #67 in Europe. Strong AI/ML research. Leuven = IMEC semiconductor hub. Sep 2027 cycle opens Oct 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"BE02","name":"Ghent University","country":"Belgium","city":"Ghent","flag":"🇧🇪",
     "qs_rank":"189","qs_num":189,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"CS · AI · Data","check_url":"https://studiekiezer.ugent.be/en/master",
     "known_open":"2026-10-01","known_deadline":"2027-03-01",
     "tuition":"€3,450/yr (~₹3.1L)","language":"TOEFL 85 / IELTS 6.5",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Very affordable top-200 EU degree. Ghent = top student city Belgium. Sep 2027.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    {"id":"BE03","name":"Vrije Universiteit Brussel (VUB)","country":"Belgium","city":"Brussels","flag":"🇧🇪",
     "qs_rank":"501-550","qs_num":525,
     "program":"MSc Applied CS / MSc AI Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.vub.be/en/studying-vub/international-students/",
     "known_open":"2026-10-01","known_deadline":"2027-03-01",
     "tuition":"€4,175/yr (~₹3.8L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"High",
     "notes":"Brussels = EU capital & NATO HQ. English-taught MSc. Strong fintech/ML industry links.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    # ══════════════════════════════════════════════════════════
    # 🇨🇭  SWITZERLAND  (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"CH01","name":"ETH Zurich","country":"Switzerland","city":"Zurich","flag":"🇨🇭",
     "qs_rank":"7","qs_num":7,
     "program":"MSc CS / MSc Data Science / MSc AI",
     "stream":"CS · AI · Data","check_url":"https://master.inf.ethz.ch/",
     "known_open":"2026-11-01","known_deadline":"2026-12-15",
     "tuition":"CHF 1,460/semester (~₹1.4L/sem)","language":"English — no TOEFL required",
     "gpa_min_pct":80,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"EU-adjacent work rights","chance":"Reach",
     "notes":"QS #7 globally. ~10% acceptance. Dec 2026 deadline. GRE 168Q + 4 papers is your edge. Apply alongside easier options.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","All publications"]},

    {"id":"CH02","name":"EPFL — École Polytechnique Fédérale de Lausanne","country":"Switzerland","city":"Lausanne","flag":"🇨🇭",
     "qs_rank":"27","qs_num":27,
     "program":"MSc CS / MSc Data Science / MSc AI",
     "stream":"CS · AI · Data","check_url":"https://www.epfl.ch/education/master/programs/",
     "known_open":"2026-11-01","known_deadline":"2026-12-15",
     "tuition":"CHF 1,460/semester (~₹1.4L/sem)","language":"English — TOEFL/IELTS optional",
     "gpa_min_pct":80,"toefl":False,"aps":False,"police":False,"medical":False,
     "post_study":"EU-adjacent work rights","chance":"Reach",
     "notes":"QS #27. World-class AI research. Your 4 papers and GRE 324 are key differentiators. Dec 2026 deadline.",
     "docs":["Passport","Transcript","CV","SOP","2 LORs","All publications"]},

    # ══════════════════════════════════════════════════════════
    # 🇩🇰  DENMARK  (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"DK01","name":"Technical University of Denmark (DTU)","country":"Denmark","city":"Kongens Lyngby","flag":"🇩🇰",
     "qs_rank":"118","qs_num":118,
     "program":"MSc CS / MSc Data Science / MSc AI & Cloud",
     "stream":"AI · CS · Cloud","check_url":"https://www.dtu.dk/english/education/msc/programmes",
     "known_open":"2026-09-01","known_deadline":"2027-01-15",
     "tuition":"DKK 80,000/yr (~₹9L) for non-EU","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"QS #118. Erasmus Mundus programs available. Sep 2027 intake opens Sep 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"DK02","name":"University of Copenhagen","country":"Denmark","city":"Copenhagen","flag":"🇩🇰",
     "qs_rank":"97","qs_num":97,
     "program":"MSc CS / MSc Data Science / MSc AI",
     "stream":"CS · AI · Data","check_url":"https://www.ku.dk/english/apply/",
     "known_open":"2026-09-01","known_deadline":"2027-01-15",
     "tuition":"DKK 80,000/yr (~₹9L) for non-EU","language":"TOEFL 88 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"QS #97. Copenhagen = world's happiest city. Sep 2027 cycle opens Sep 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    # ══════════════════════════════════════════════════════════
    # 🇳🇴  NORWAY  (1 university)
    # ══════════════════════════════════════════════════════════
    {"id":"NO01","name":"NTNU — Norwegian University of Science and Technology","country":"Norway","city":"Trondheim","flag":"🇳🇴",
     "qs_rank":"97","qs_num":97,
     "program":"MSc CS / MSc AI / MSc Data Science / MSc Software Engineering",
     "stream":"AI · CS · Software","check_url":"https://www.ntnu.edu/studies/master",
     "known_open":"2026-10-01","known_deadline":"2027-04-01",
     "tuition":"NOK 8,300/semester (~₹67K/sem) — near free","language":"TOEFL 92 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU/EEA work rights","chance":"Medium-High",
     "notes":"QS #97 — nearly free tuition for all nationalities. Norway = highest CS salaries globally. Sep 2027 cycle opens Oct 2026.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    # ══════════════════════════════════════════════════════════
    # 🇫🇷  FRANCE  (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"FR01","name":"Sorbonne University","country":"France","city":"Paris","flag":"🇫🇷",
     "qs_rank":"73","qs_num":73,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.sorbonne-universite.fr/en/education/",
     "known_open":"2026-11-01","known_deadline":"2027-03-15",
     "tuition":"€3,770/yr (~₹3.4L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"QS #73 at ₹3.4L/yr — best value QS top-100. Sep 2027 cycle. Paris = global AI hub (Meta, Google, DeepMind EU labs).",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"FR02","name":"Université Paris-Saclay","country":"France","city":"Saclay","flag":"🇫🇷",
     "qs_rank":"87","qs_num":87,
     "program":"MSc CS / MSc AI / MSc Data Science",
     "stream":"AI · CS · Data","check_url":"https://www.universite-paris-saclay.fr/en/admission",
     "known_open":"2026-11-01","known_deadline":"2027-03-15",
     "tuition":"€3,770/yr (~₹3.4L)","language":"TOEFL 90 / IELTS 6.5",
     "gpa_min_pct":65,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights","chance":"Medium-High",
     "notes":"QS #87. Microsoft Research, Google, CEA labs all on campus. World-class AI cluster. Sep 2027.",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    # ══════════════════════════════════════════════════════════
    # 🇵🇹  PORTUGAL  (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"PT01","name":"Instituto Superior Técnico (IST) — Universidade de Lisboa","country":"Portugal","city":"Lisbon","flag":"🇵🇹",
     "qs_rank":"221","qs_num":221,
     "program":"MSc CS / MSc AI / MSc Data Science & Engineering",
     "stream":"AI · CS · Data","check_url":"https://tecnico.ulisboa.pt/en/students/admissions/",
     "known_open":"2026-11-01","known_deadline":"2027-03-31",
     "tuition":"€7,300/yr (~₹6.6L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":60,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights + D3 Tech Visa","chance":"High",
     "notes":"QS #221. Portugal D3 Tech Visa allows work post-study. Lisbon = fastest-growing EU tech hub (Farfetch, Feedzai).",
     "docs":["Passport","Transcript","TOEFL","CV","PS","2 LORs"]},

    {"id":"PT02","name":"Universidade do Porto","country":"Portugal","city":"Porto","flag":"🇵🇹",
     "qs_rank":"285","qs_num":285,
     "program":"MSc CS / MSc AI / MSc Software Engineering",
     "stream":"CS · AI · Software","check_url":"https://sigarra.up.pt/up/en/web_page.initial",
     "known_open":"2026-11-01","known_deadline":"2027-03-31",
     "tuition":"€5,600/yr (~₹5L)","language":"TOEFL 80 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"EU work rights + D3 Tech Visa","chance":"High",
     "notes":"QS #285. Porto — low cost of living, high quality of life. Strong engineering faculty.",
     "docs":["Passport","Transcript","TOEFL","CV","PS"]},

    # ══════════════════════════════════════════════════════════
    # 🇦🇪  UAE  (2 universities)
    # ══════════════════════════════════════════════════════════
    {"id":"AE01","name":"Mohamed bin Zayed University of AI (MBZUAI)","country":"UAE","city":"Abu Dhabi","flag":"🇦🇪",
     "qs_rank":"unranked","qs_num":9999,
     "program":"MSc AI / MSc Machine Learning / MSc Computer Vision / MSc NLP",
     "stream":"AI · ML · CV · NLP","check_url":"https://mbzuai.ac.ae/admissions/",
     "known_open":"2026-09-01","known_deadline":"2027-01-15",
     "tuition":"FREE + monthly stipend AED 5,500 (~₹1.25L/month)","language":"TOEFL 80 / IELTS 6.5",
     "gpa_min_pct":None,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"UAE Golden Visa eligible","chance":"Medium-High",
     "notes":"FULLY FUNDED — free tuition + AED 5,500/month stipend (~₹15L/yr). World's first AI-only grad university. Your 4 papers and GRE 324 are very competitive here.",
     "docs":["Passport","Transcript","TOEFL","CV","SOP","2 LORs","Research statement"]},

    {"id":"AE02","name":"Khalifa University","country":"UAE","city":"Abu Dhabi","flag":"🇦🇪",
     "qs_rank":"271","qs_num":271,
     "program":"MSc CS / MSc AI / MSc Cybersecurity / MSc Data Science",
     "stream":"AI · CS · Cyber","check_url":"https://www.ku.ac.ae/admissions",
     "known_open":"2026-09-01","known_deadline":"2026-12-15",
     "tuition":"AED 35,000/yr (~₹8L) — 50–100% scholarships available","language":"TOEFL 79 / IELTS 6.0",
     "gpa_min_pct":55,"toefl":True,"aps":False,"police":False,"medical":False,
     "post_study":"UAE Golden Visa eligible","chance":"High",
     "notes":"QS #271. Partial-to-full scholarships often awarded. Abu Dhabi = FAANG Middle East expansion hub.",
     "docs":["Passport","Transcript","TOEFL","CV","SOP","2 LORs"]},
]

if __name__ == "__main__":
    # Quick test: print profile and count universities
    print(f"Profile loaded for {PROFILE['name']}")
    print(f"Total universities in tracker: {len(UNIVERSITIES)}")
    # Optionally, you can integrate with your tracker app here.
